apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: dummy-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080