apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: docker.io/bhatiasunny/my-preview-app
  newTag: pr-46-1ec1d98fb47a1942113cfc064d41be6bf27302b1