apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: docker.io/bhatiasunny/my-preview-app
  newTag: pr-50-35cef5cb72f0603ac1076cb283b511668fa92de3