apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: sunbha
        repo: preview-env-source-code
      tokenRef:
        secretName: argocd-token
        key: token
      labels:
        - preview
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'myapp-pr-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/SunBha/preview-env-source-code.git'
        targetRevision: main
        # 'preview-pr-{{.number}}'
        path: kustomize-preview-app/ 
        kustomize:
          images:
            - 'docker.io/bhatiasunny/my-preview-app:{{.head_short_sha_7}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-pr-{{.number}}'
      syncPolicy:
        automated:
          prune: true  
          selfHeal: true
        syncOptions:
        - CreateNamespace=true