apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: sunbha
        repo: preview-env-source-code
      tokenRef:
        secretName: argocd-token
        key: token
      labels:
        - preview
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'myapp-{{.branch}}'
    spec:
      source:
        repoURL: 'https://github.com/SunBha/preview-env-manifests.git'
        targetRevision: HEAD
        path: kustomize-preview-app/
        kustomize:
          images:
            - 'docker.io/bhatiasunny/my-preview-app:{{.head_short_sha_7}}'        
          patches:
            - target:
                kind: Deployment
                name: simple-deployment
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/0
                  value: 
                    name: GIT_BRANCH
                    value: '{{.branch_slug}}' 
                - op: replace
                  path: /spec/template/spec/containers/0/env/1
                  value: 
                    name: GIT_HASH
                    value: '{{.head_short_sha_7}}' 
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.branch_slug}}'
      syncPolicy:
        automated:
          prune: true  
        syncOptions:
        - CreateNamespace=true 
